version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
      # - postgres_test
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    env_file:
      - ./.env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Souhal0517
      - POSTGRES_DB=learn-python-api-development
    volumes:
      - postgres-db:/var/lib/postgresql/data
  # postgres_test:
  #   image: postgres
  #   environment:
  #     - POSTGRES_PASSWORD=Souhal0517_test
  #     - POSTGRES_DB=learn-python-api-development_test
  #   volumes:
  #     - postgres-test-db:/var/lib/postgresql/data
volumes:
  postgres-db:
  # postgres-test-db: